### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'on_delete'

### ISSUE THREAD

**Issue by xmzhangs** [ShunfuSheng/flea-market#3]
Traceback (most recent call last):
  File "C:\Users\40690\PycharmProjects\flea-market-master\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\40690\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\40690\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "C:\Users\40690\AppData\Local\Programs\Python\Python39\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\40690\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
  File "C:\Users\40690\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\40690\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\40690\PycharmProjects\flea-market-master\login\models.py", line 24, in <module>
    class AuthGroupPermissions(models.Model):
  File "C:\Users\40690\PycharmProjects\flea-market-master\login\models.py", line 26, in AuthGroupPermissions
    group = models.ForeignKey(AuthGroup)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

这个是什么问题，怎么解决？

**Comment by mazhenwei793** [comment]
你好，你这个问题解决了吗
